namespace XmlApp.ViewModels
{
    public class GumrukDataTableModel
    {
        public string FaturaNo { get; set; }
        public string FaturaTuru { get; set; }
        public string FaturaTarih { get; set; }
        public string OdemeSekli { get; set; }
        public string FaturaTeslimSekli { get; set; }
        public decimal FaturaTutari { get; set; }
        public string FaturaParaBirimi { get; set; }
        public string FonDekontDekontNo { get; set; }
        public string FonDekontTarih { get; set; }
        public decimal FonDekontTutar { get; set; }
        public string FonDekontTutarPB { get; set; }
        public decimal FonDekontKullanilan { get; set; }
        public string FonDekontKullanilanPB { get; set; }
        public decimal FonDekontKullanilanDolar { get; set; }
        public string BelgeNo { get; set; }
        public string SerbestBolgeAdi { get; set; }
        public string KayitTarihi { get; set; }
        public string DisReferansNo { get; set; }
        public string GumrukId { get; set; }
        public string FormDurumu { get; set; }
        public string FirmaTicaretUnvani { get; set; }
        public string FirmaFaaliyetRuhsatiNo { get; set; }
        public string FirmaFaaliyetRuhsatiKonusu { get; set; }
        public string DepoKullanimBelgeliFirma { get; set; }
        public string DepoKullanimBelgeNo { get; set; }
        public string FormuDolduraninAdi { get; set; }
        public string FirmaTelefonu { get; set; }
        public string GumBeyannameNo { get; set; }
        public string GumTescilTarihi { get; set; }
        public string GumTescilNo { get; set; }
        public string GumIslemiOnaylayaninAdiSoyadi { get; set; }
        public string GumMuhOnaylayanAdi { get; set; }
        public string GumMuhTescilNumarasi { get; set; }
        public string GumMuhTescilTarihi { get; set; }
        public string AdiTicaretUnvani { get; set; }
        public string Adresi { get; set; }
        public string PostaKodu { get; set; }
        public string Ulke { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Telefon3 { get; set; }
        public string Faks1 { get; set; }
        public string Faks2 { get; set; }
        public string EPosta { get; set; }
        public string OrtakDepo { get; set; }
        public string Kantar { get; set; }
        public string YuklemeBosaltma { get; set; }
        public string IsMakinasi { get; set; }
        public string Ellecleme { get; set; }
        public string KoordinasyonHizmeti { get; set; }
        public string DigerTalepEdilenHizmetler { get; set; }
        public string SevkiyatSekliAdi { get; set; }
        public int? SbifGumrukBilgileriId { get; set; }
        public int? SbifBilgiFisiId { get; set; }
        public decimal MalKalemUsdToplami { get; set; }
        public string MalKalemId { get; set; }
        public int SiraNo { get; set; }
        public int GumrukSiraNo { get; set; }
        public string? ReferansFormTipi { get; set; }
        public string? ReferansFormNo { get; set; }
        public int ReferansFormYil { get; set; }
        public int ReferansFormSiraNo { get; set; }
        public string gtip { get; set; }
        public string Cins { get; set; }
        public string Mensei { get; set; }
        public string GeldigiGidecegiUlke { get; set; }
        public decimal BirinciMiktar { get; set; }
        public string BirinciBirim { get; set; }
        public string KapTuru { get; set; }
        public int KapAdedi { get; set; }
        public decimal MalBedeli { get; set; }
        public string MalBedeliParaBirimi { get; set; }
        public decimal NavlunBedeli { get; set; }
        public string NavlunBedeliParaBirimi { get; set; }
        public decimal SigortaBedeli { get; set; }
        public string SigortaBedeliParaBirimi { get; set; }
        public decimal BrutAgirlik { get; set; }
        public string MalKalemTeslimSekli { get; set; }
        public string VergiKimlikNo { get; set; }
        public string VergiDairesi { get; set; }
        public string AdiUnvani { get; set; }
        public string WebAdresi { get; set; }
        public string IslemYonu { get; set; }
        public string IslemTuru { get; set; }
        public string IslemKonusu { get; set; }
        public string IslemKonusuTicari { get; set; }
        public string IslemKonusuTicariOlmayan { get; set; }
    }
}
